### ISSUE TITLE
Base image Vulnerabilities - USN-5823-1 - libmysqlclient21

### ISSUE THREAD

**Issue by turbra** [timescale/timescaledb-docker-ha#360]
Image: `pg14.6-ts2.9.1-p1`
Contains a handful of vulnerabilities but I want to focus on this one specifically `libmysqlclient21`
 - https://ubuntu.com/security/notices/USN-5823-1
 
Is there a specific reason as to why an alpine image is not being used instead of `ubuntu:22.04`?
In theory this would reduce the size of the image and reduce the risk of the image containing packages that are not mandatory for timescale to function, making this more efficient, secure and easier to maintain.

Open for feedback!

**Comment by graveland** [comment]
Alpine's musl libc causes some compatibility problems sometimes, and glibc has been more well tested over time. Also, the base image sizes for ubuntu and alpine are 70mb vs 8mb, but `pg14.6-ts2.9.1-p1` is 750mb, so the difference is is really negligible. Since the parts that make the image large are going to be the same with alpine vs ubuntu, it really doesn't make that big of a size difference.

I haven't followed the dependency chain to see where the MySQL client is being installed from, but my guess is possibly something PostGIS-related? If so, then it'll get picked up in Alpine too by us installing PostGIS there as well.

Regarding that specific vulnerability report though, since the container isn't running a MySQL server, it's going to be pretty hard to exploit it! Somebody would have to exploit a PostgreSQL vulnerability that gets them local access inside the container before they would have access to the vulnerable mysql binaries. Even then, that doesn't actually escalate anything since MySQL doesn't use setuid permissions, and the container (by default) is running without elevated privileges.

The https://hub.docker.com/r/timescale/timescaledb images are much more bare-bones if you want to run something with fewer dependencies though.

**Comment by turbra** [comment]
Thanks @graveland, all excellent points. In order to exploit would be difficult to say the least.  These things end up on reports and reducing the _noise_ which limits the back and forth conversations about the findings is always helpful!

**Comment by graveland** [comment]
Absolutely agreed!
