### ISSUE TITLE
How do I activate postgis on the image timescale/timescaledb-ha:pg15 ?

### ISSUE THREAD

**Issue by hermesalvesbr** [timescale/timescaledb-docker-ha#400]
I just ran the timescale/timescaledb-ha:pg15 image, however my software doesn't detect postgis. 
Do I need some environment variable to activate? 

I tried POSTGIS_VERSIONS="3.3.3" , but that didn't work either.

![Captura de tela de 2023-07-06 15-20-18](https://github.com/timescale/timescaledb-docker-ha/assets/379850/db847018-1bad-4961-8304-722f458b07ea)

**Comment by graveland** [comment]
Are you sure the postgis extension was installed in your database? The binaries should be included, but you'd need to `CREATE EXTENSION posgis;` at the least. In psql, `\dx` should tell you.

**Comment by ArchaicDebugger** [comment]
Tried the same thing, it seems either the binaries are not installed or I'm missing something. My scenario is I'm trying out Patroni and checking if my code can work fine with the replications, but can't get past the Postgis part.

I'm using `timescale/timescaledb-ha` since the documentation says PostGIS will always be included in the builds.

**Comment by hermesalvesbr** [comment]
Hi there,

I resolved to make my own image: https://github.com/SoftagonSistemas/postgresql-15 

Now work's for me.
